/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ARAYUZLER;

import System.InfoKullanici;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author OGUZ
 */
public class KayıtOl extends javax.swing.JFrame {

    /**
     * Creates new form KayıtOl
     */
    Giris old;
    public KayıtOl(Giris x) {
        initComponents();
        old = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfEklenecekSoyAd = new javax.swing.JTextField();
        tfEklenecekSIFRE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfEklenecekID = new javax.swing.JTextField();
        jcEKLENENBOLUMLER = new javax.swing.JComboBox<>();
        tfEklenecekAd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnKullaniciEkle = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnKullaniciEkle1 = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(543, 375));
        jPanel1.setLayout(null);

        tfEklenecekSoyAd.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jPanel1.add(tfEklenecekSoyAd);
        tfEklenecekSoyAd.setBounds(190, 90, 220, 24);

        tfEklenecekSIFRE.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jPanel1.add(tfEklenecekSIFRE);
        tfEklenecekSIFRE.setBounds(190, 180, 220, 24);

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("PASSWORD:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 180, 110, 18);

        tfEklenecekID.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jPanel1.add(tfEklenecekID);
        tfEklenecekID.setBounds(190, 150, 220, 24);

        jcEKLENENBOLUMLER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcEKLENENBOLUMLER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilgisayar Muhendisligi", "Makina Muhendisligi", "Endustri Muhendisligi", "Tip Fakultesi", "Dis Hekimligi", "Elektrik Elektronik Muhendisligi" }));
        jcEKLENENBOLUMLER.setSelectedIndex(-1);
        jPanel1.add(jcEKLENENBOLUMLER);
        jcEKLENENBOLUMLER.setBounds(190, 120, 220, 21);

        tfEklenecekAd.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jPanel1.add(tfEklenecekAd);
        tfEklenecekAd.setBounds(190, 60, 220, 24);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("NAME:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 60, 100, 18);

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("ID :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 150, 26, 18);

        btnKullaniciEkle.setBackground(new java.awt.Color(0, 155, 167));
        btnKullaniciEkle.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnKullaniciEkle.setText("REGISTER");
        btnKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciEkleActionPerformed(evt);
            }
        });
        jPanel1.add(btnKullaniciEkle);
        btnKullaniciEkle.setBounds(90, 250, 140, 31);

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("DEPARTMENT:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 120, 110, 18);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("SURNAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 90, 100, 18);

        btnKullaniciEkle1.setBackground(new java.awt.Color(0, 155, 167));
        btnKullaniciEkle1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnKullaniciEkle1.setText("CANCEL");
        btnKullaniciEkle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciEkle1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKullaniciEkle1);
        btnKullaniciEkle1.setBounds(260, 250, 140, 31);

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/LoginBackgroun.jpg"))); // NOI18N
        jPanel1.add(lblBackGround);
        lblBackGround.setBounds(0, 0, 550, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean KontrolEt(){
        if (tfEklenecekAd.getText().equals("") == false && tfEklenecekSoyAd.getText().equals("") ==false && tfEklenecekID.getText().equals("") == false && tfEklenecekSIFRE.getText().equals("") == false && jcEKLENENBOLUMLER.getSelectedIndex() != -1) {
            return true;
        }
        return false;
    }
    private void btnKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciEkleActionPerformed
        if (!KontrolEt()) {
            JOptionPane.showMessageDialog(null, "Please fill in the blanks !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(null, "Would like to be registered according to the information you filled ?","Register ? ?", JOptionPane.YES_NO_OPTION);
            if(InfoKullanici.isIDExist(tfEklenecekID.getText())){
                JOptionPane.showMessageDialog(null, "Existing user with this id");
            }
            else{
                if(reply == JOptionPane.YES_NO_OPTION){
                    try {
                        InfoKullanici.Kullanici_Ekle(tfEklenecekAd.getText(), tfEklenecekSoyAd.getText(), jcEKLENENBOLUMLER.getSelectedItem().toString(), tfEklenecekID.getText(), tfEklenecekSIFRE.getText());
                        JOptionPane.showMessageDialog(null, "WELCOME TO AYBU LIBRARY");
                        old.setVisible(true);
                        this.dispose();
                    } catch (IOException ex) {
                        Logger.getLogger(KayıtOl.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnKullaniciEkleActionPerformed

    private void btnKullaniciEkle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciEkle1ActionPerformed
       this.dispose();
       old.setVisible(true);
    }//GEN-LAST:event_btnKullaniciEkle1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKullaniciEkle;
    private javax.swing.JButton btnKullaniciEkle1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcEKLENENBOLUMLER;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JTextField tfEklenecekAd;
    private javax.swing.JTextField tfEklenecekID;
    private javax.swing.JTextField tfEklenecekSIFRE;
    private javax.swing.JTextField tfEklenecekSoyAd;
    // End of variables declaration//GEN-END:variables
}
