/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ARAYUZLER;

import System.InfoKitap;
import Kitap.*;
import System.InfoKullanici;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OGUZ
 */
public class Kullanici_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Kullanici_GUI
     */
    public void butonlariayarla(){
      btnMevcutKitaplar1.setContentAreaFilled(false);
      // btnMevcutKitaplar1.setFocusPainted(false);
     //  btnMevcutKitaplar1.setBorderPainted(false);
        btnSifreDegis.setContentAreaFilled(false);
       // btnSifreDegis.setFocusPainted(false);
       // btnSifreDegis.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
       // btnSifreDegis1.setFocusPainted(false);
       // btnSifreDegis1.setBorderPainted(false);
        btnSahipOlunanKitaplar.setContentAreaFilled(false);
       // btnSahipOlunanKitaplar.setFocusPainted(false);
       // btnSahipOlunanKitaplar.setBorderPainted(false);
        btnKitapAra.setContentAreaFilled(false);
        btnHome.setContentAreaFilled(false);
        btnHome1.setContentAreaFilled(false);
        btnHome2.setContentAreaFilled(false);
        btnHome3.setContentAreaFilled(false);
    }
    public void tablelariAyarla(){
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
         jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
         jScrollPane3.setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);
         jScrollPane4.setOpaque(false);
        jScrollPane4.getViewport().setOpaque(false);
         jScrollPane5.setOpaque(false);
        jScrollPane5.getViewport().setOpaque(false);
         jScrollPane6.setOpaque(false);
        jScrollPane6.getViewport().setOpaque(false);
         jScrollPane8.setOpaque(false);
        jScrollPane8.getViewport().setOpaque(false);
        jScrollPane7.setOpaque(false);
        jScrollPane7.getViewport().setOpaque(false);
      
    }
    
    Giris old;
    ArrayList<Kitap> kitap;
    ArrayList<BasiliKitap> basili;
    ArrayList<E_Kitap> elek;
    ArrayList<Roman>  roman;
    ArrayList<Dergi> dergi;
    ArrayList<Ansiklopedi> ansiklopedi;
    
    public Kullanici_GUI(Giris x) {
        initComponents();
        butonlariayarla();
       tablelariAyarla();
       jpanelSecimler.setVisible(false);
         kitap = InfoKitap.getKitapListem();
       basili = InfoKitap.getBasili();
       elek = InfoKitap.getEkitap();
       roman = InfoKitap.getRomans();
       dergi = InfoKitap.getDergi();
       ansiklopedi = InfoKitap.getAnsiklopedi();
        old = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpAnapanel = new javax.swing.JPanel();
        lbluserid1 = new javax.swing.JLabel();
        lbluserid = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnMevcutKitaplar1 = new javax.swing.JButton();
        btnSifreDegis = new javax.swing.JButton();
        lbluserid3 = new javax.swing.JLabel();
        btnKitapAra = new javax.swing.JButton();
        btnSahipOlunanKitaplar = new javax.swing.JButton();
        lbluserid2 = new javax.swing.JLabel();
        lbluserid4 = new javax.swing.JLabel();
        jpSifreDegis = new javax.swing.JPanel();
        jPassEskiKullaniciSifre = new javax.swing.JPasswordField();
        jPassYeniKullaniciSifre = new javax.swing.JPasswordField();
        jPassYeniKullaniciSifre2 = new javax.swing.JPasswordField();
        lbluserid5 = new javax.swing.JLabel();
        lbluserid6 = new javax.swing.JLabel();
        lbluserid7 = new javax.swing.JLabel();
        btnShowMoreDetail1 = new javax.swing.JButton();
        btnHome3 = new javax.swing.JButton();
        jpSahipOlunanKitaplariGoruntule = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableMevcutKitaplar = new javax.swing.JTable();
        btnShowMoreDetail = new javax.swing.JButton();
        btnIadeEt = new javax.swing.JButton();
        btnHome2 = new javax.swing.JButton();
        jpKitapAra = new javax.swing.JPanel();
        btnHome1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableAranan = new javax.swing.JTable();
        jpanelSecimler = new javax.swing.JPanel();
        PanelIDileAra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfSearchedId = new javax.swing.JTextField();
        panelAdİleAra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfSearchedName = new javax.swing.JTextField();
        jCheckSearchByName = new javax.swing.JCheckBox();
        jCheckSearchbyID = new javax.swing.JCheckBox();
        btnAra = new javax.swing.JButton();
        btnOduncAl = new javax.swing.JButton();
        jPMevcutKitaplariGoruntule = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelShowAll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKitap = new javax.swing.JTable();
        panelShowBasili = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBasili = new javax.swing.JTable();
        panelShowEKitap = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEkitap = new javax.swing.JTable();
        panelShowRoman = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRoman = new javax.swing.JTable();
        panelShowAnsiklopedi = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableAnsiklopedi = new javax.swing.JTable();
        panelShowDergi = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableDergi = new javax.swing.JTable();
        btnShowDetail = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout());

        jpAnapanel.setOpaque(false);

        lbluserid1.setFont(new java.awt.Font("Cambria Math", 1, 10)); // NOI18N
        lbluserid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluserid1.setText("SEE YOUR BOOKS");

        lbluserid.setFont(new java.awt.Font("Cambria Math", 1, 10)); // NOI18N
        lbluserid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluserid.setText("EXIT");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/exit.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMevcutKitaplar1.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnMevcutKitaplar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/rsz_showallbook.png"))); // NOI18N
        btnMevcutKitaplar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMevcutKitaplar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMevcutKitaplar1ActionPerformed(evt);
            }
        });

        btnSifreDegis.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnSifreDegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/changepasswd.png"))); // NOI18N
        btnSifreDegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSifreDegisActionPerformed(evt);
            }
        });

        lbluserid3.setFont(new java.awt.Font("Cambria Math", 1, 10)); // NOI18N
        lbluserid3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluserid3.setText("CHANGEPASSWD");

        btnKitapAra.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnKitapAra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/rsz_searchbook.png"))); // NOI18N
        btnKitapAra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKitapAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapAraActionPerformed(evt);
            }
        });

        btnSahipOlunanKitaplar.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnSahipOlunanKitaplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/alinankitaplarigoruntule.png"))); // NOI18N
        btnSahipOlunanKitaplar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSahipOlunanKitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSahipOlunanKitaplarActionPerformed(evt);
            }
        });

        lbluserid2.setFont(new java.awt.Font("Cambria Math", 1, 10)); // NOI18N
        lbluserid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluserid2.setText("SHOW ALL BOOK");

        lbluserid4.setFont(new java.awt.Font("Cambria Math", 1, 10)); // NOI18N
        lbluserid4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluserid4.setText("SEARCH A BOOK");

        javax.swing.GroupLayout jpAnapanelLayout = new javax.swing.GroupLayout(jpAnapanel);
        jpAnapanel.setLayout(jpAnapanelLayout);
        jpAnapanelLayout.setHorizontalGroup(
            jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnapanelLayout.createSequentialGroup()
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnapanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSifreDegis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbluserid3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbluserid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAnapanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMevcutKitaplar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbluserid2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbluserid4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnKitapAra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAnapanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbluserid1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSahipOlunanKitaplar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jpAnapanelLayout.setVerticalGroup(
            jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnapanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMevcutKitaplar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSahipOlunanKitaplar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnKitapAra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbluserid2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbluserid1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbluserid4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(btnSifreDegis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAnapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbluserid3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluserid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel2.add(jpAnapanel, "card2");

        jpSifreDegis.setOpaque(false);

        jPassEskiKullaniciSifre.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jPassYeniKullaniciSifre.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        jPassYeniKullaniciSifre2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N

        lbluserid5.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbluserid5.setText("NEW PASSWORD :");

        lbluserid6.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbluserid6.setText("OLD PASSWORD :");

        lbluserid7.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbluserid7.setText("NEW PASSWORD :");

        btnShowMoreDetail1.setBackground(new java.awt.Color(0, 155, 167));
        btnShowMoreDetail1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnShowMoreDetail1.setText("CHANGE PASSWORD");
        btnShowMoreDetail1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowMoreDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMoreDetail1ActionPerformed(evt);
            }
        });

        btnHome3.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/rsz_home.png"))); // NOI18N
        btnHome3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSifreDegisLayout = new javax.swing.GroupLayout(jpSifreDegis);
        jpSifreDegis.setLayout(jpSifreDegisLayout);
        jpSifreDegisLayout.setHorizontalGroup(
            jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSifreDegisLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSifreDegisLayout.createSequentialGroup()
                        .addComponent(btnHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSifreDegisLayout.createSequentialGroup()
                        .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnShowMoreDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpSifreDegisLayout.createSequentialGroup()
                                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbluserid5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbluserid6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbluserid7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPassEskiKullaniciSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jPassYeniKullaniciSifre)
                                    .addComponent(jPassYeniKullaniciSifre2))))
                        .addGap(332, 332, 332))))
        );
        jpSifreDegisLayout.setVerticalGroup(
            jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSifreDegisLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserid6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassEskiKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserid7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassYeniKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSifreDegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserid5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassYeniKullaniciSifre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnShowMoreDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2.add(jpSifreDegis, "card6");

        jpSahipOlunanKitaplariGoruntule.setOpaque(false);

        jTableMevcutKitaplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book Type", "Subject", "Delivery Date"
            }
        ));
        jScrollPane7.setViewportView(jTableMevcutKitaplar);

        btnShowMoreDetail.setBackground(new java.awt.Color(0, 155, 167));
        btnShowMoreDetail.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnShowMoreDetail.setText("SHOW MORE DETAIL");
        btnShowMoreDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowMoreDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMoreDetailActionPerformed(evt);
            }
        });

        btnIadeEt.setBackground(new java.awt.Color(0, 155, 167));
        btnIadeEt.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnIadeEt.setText("GIVE BACK THE BOOK");
        btnIadeEt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIadeEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIadeEtActionPerformed(evt);
            }
        });

        btnHome2.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/rsz_home.png"))); // NOI18N
        btnHome2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSahipOlunanKitaplariGoruntuleLayout = new javax.swing.GroupLayout(jpSahipOlunanKitaplariGoruntule);
        jpSahipOlunanKitaplariGoruntule.setLayout(jpSahipOlunanKitaplariGoruntuleLayout);
        jpSahipOlunanKitaplariGoruntuleLayout.setHorizontalGroup(
            jpSahipOlunanKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createSequentialGroup()
                .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createSequentialGroup()
                        .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnShowMoreDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnIadeEt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSahipOlunanKitaplariGoruntuleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpSahipOlunanKitaplariGoruntuleLayout.setVerticalGroup(
            jpSahipOlunanKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jpSahipOlunanKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowMoreDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIadeEt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnHome2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jpSahipOlunanKitaplariGoruntule, "card5");

        jpKitapAra.setOpaque(false);

        btnHome1.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/rsz_home.png"))); // NOI18N
        btnHome1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        jScrollPane8.setOpaque(false);

        tableAranan.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableAranan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Publisher", "Type", "Subject"
            }
        ));
        tableAranan.setOpaque(false);
        jScrollPane8.setViewportView(tableAranan);

        jpanelSecimler.setOpaque(false);
        jpanelSecimler.setLayout(new java.awt.CardLayout());

        PanelIDileAra.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID : ");

        tfSearchedId.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N

        javax.swing.GroupLayout PanelIDileAraLayout = new javax.swing.GroupLayout(PanelIDileAra);
        PanelIDileAra.setLayout(PanelIDileAraLayout);
        PanelIDileAraLayout.setHorizontalGroup(
            PanelIDileAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIDileAraLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSearchedId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelIDileAraLayout.setVerticalGroup(
            PanelIDileAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIDileAraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIDileAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearchedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelSecimler.add(PanelIDileAra, "card2");

        panelAdİleAra.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BOOK NAME :");

        tfSearchedName.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N

        javax.swing.GroupLayout panelAdİleAraLayout = new javax.swing.GroupLayout(panelAdİleAra);
        panelAdİleAra.setLayout(panelAdİleAraLayout);
        panelAdİleAraLayout.setHorizontalGroup(
            panelAdİleAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdİleAraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tfSearchedName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAdİleAraLayout.setVerticalGroup(
            panelAdİleAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdİleAraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdİleAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSearchedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelSecimler.add(panelAdİleAra, "card3");

        jCheckSearchByName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jCheckSearchByName.setText("SEARCH BY NAME");
        jCheckSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSearchByNameActionPerformed(evt);
            }
        });

        jCheckSearchbyID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jCheckSearchbyID.setText("SEARCH BY ID");
        jCheckSearchbyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSearchbyIDActionPerformed(evt);
            }
        });

        btnAra.setBackground(new java.awt.Color(0, 155, 167));
        btnAra.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnAra.setText("SEARCH");
        btnAra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        btnOduncAl.setBackground(new java.awt.Color(0, 155, 167));
        btnOduncAl.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnOduncAl.setText("TAKE THE BOOK");
        btnOduncAl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOduncAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpKitapAraLayout = new javax.swing.GroupLayout(jpKitapAra);
        jpKitapAra.setLayout(jpKitapAraLayout);
        jpKitapAraLayout.setHorizontalGroup(
            jpKitapAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKitapAraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpKitapAraLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jpanelSecimler, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jCheckSearchbyID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckSearchByName)
                .addGap(103, 103, 103))
            .addGroup(jpKitapAraLayout.createSequentialGroup()
                .addGroup(jpKitapAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpKitapAraLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpKitapAraLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOduncAl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpKitapAraLayout.setVerticalGroup(
            jpKitapAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpKitapAraLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jpKitapAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOduncAl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jpKitapAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpKitapAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckSearchbyID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpanelSecimler, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel2.add(jpKitapAra, "card4");

        jPMevcutKitaplariGoruntule.setOpaque(false);

        jTabbedPane1.setBackground(new java.awt.Color(236, 64, 64));

        panelShowAll.setOpaque(false);
        panelShowAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelShowAllMouseClicked(evt);
            }
        });
        panelShowAll.setLayout(new javax.swing.OverlayLayout(panelShowAll));

        jScrollPane1.setOpaque(false);

        tableKitap.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableKitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Publisher", "Date of Issue"
            }
        ));
        tableKitap.setOpaque(false);
        jScrollPane1.setViewportView(tableKitap);

        panelShowAll.add(jScrollPane1);

        jTabbedPane1.addTab("All Books", panelShowAll);

        panelShowBasili.setOpaque(false);
        panelShowBasili.setLayout(new javax.swing.OverlayLayout(panelShowBasili));

        jScrollPane2.setOpaque(false);

        tableBasili.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableBasili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Publisher", "Date of Issue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBasili.setOpaque(false);
        jScrollPane2.setViewportView(tableBasili);

        panelShowBasili.add(jScrollPane2);

        jTabbedPane1.addTab("Printed Books", panelShowBasili);

        panelShowEKitap.setOpaque(false);
        panelShowEKitap.setLayout(new javax.swing.OverlayLayout(panelShowEKitap));

        jScrollPane3.setOpaque(false);

        tableEkitap.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableEkitap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Publisher", "Date of Issue", "Language"
            }
        ));
        tableEkitap.setOpaque(false);
        jScrollPane3.setViewportView(tableEkitap);

        panelShowEKitap.add(jScrollPane3);

        jTabbedPane1.addTab("E-Books", panelShowEKitap);

        panelShowRoman.setOpaque(false);
        panelShowRoman.setLayout(new javax.swing.OverlayLayout(panelShowRoman));

        jScrollPane4.setOpaque(false);

        tableRoman.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableRoman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Publisher", "Date of Issue", "Author", "Type"
            }
        ));
        tableRoman.setOpaque(false);
        jScrollPane4.setViewportView(tableRoman);

        panelShowRoman.add(jScrollPane4);

        jTabbedPane1.addTab("Novel", panelShowRoman);

        panelShowAnsiklopedi.setOpaque(false);
        panelShowAnsiklopedi.setLayout(new javax.swing.OverlayLayout(panelShowAnsiklopedi));

        jScrollPane5.setOpaque(false);

        tableAnsiklopedi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableAnsiklopedi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Publisher", "Date of Issue", "Subject"
            }
        ));
        tableAnsiklopedi.setOpaque(false);
        jScrollPane5.setViewportView(tableAnsiklopedi);

        panelShowAnsiklopedi.add(jScrollPane5);

        jTabbedPane1.addTab("Encyclopedia", panelShowAnsiklopedi);

        panelShowDergi.setOpaque(false);
        panelShowDergi.setLayout(new javax.swing.OverlayLayout(panelShowDergi));

        jScrollPane6.setOpaque(false);

        tableDergi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tableDergi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Publisher", "Date of Issue", "Type", "Editor"
            }
        ));
        tableDergi.setOpaque(false);
        jScrollPane6.setViewportView(tableDergi);

        panelShowDergi.add(jScrollPane6);

        jTabbedPane1.addTab("Magazine", panelShowDergi);

        btnShowDetail.setBackground(new java.awt.Color(0, 155, 167));
        btnShowDetail.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnShowDetail.setText("SHOW MORE DETAIL");
        btnShowDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Cambria Math", 1, 11)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/rsz_home.png"))); // NOI18N
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMevcutKitaplariGoruntuleLayout = new javax.swing.GroupLayout(jPMevcutKitaplariGoruntule);
        jPMevcutKitaplariGoruntule.setLayout(jPMevcutKitaplariGoruntuleLayout);
        jPMevcutKitaplariGoruntuleLayout.setHorizontalGroup(
            jPMevcutKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMevcutKitaplariGoruntuleLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPMevcutKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMevcutKitaplariGoruntuleLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(142, Short.MAX_VALUE))
                    .addGroup(jPMevcutKitaplariGoruntuleLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnShowDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPMevcutKitaplariGoruntuleLayout.setVerticalGroup(
            jPMevcutKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMevcutKitaplariGoruntuleLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPMevcutKitaplariGoruntuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMevcutKitaplariGoruntuleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnShowDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMevcutKitaplariGoruntuleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jPanel2.add(jPMevcutKitaplariGoruntule, "card3");

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 480);

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/kullaniciguiBackground.png"))); // NOI18N
        jPanel1.add(lblbackground);
        lblbackground.setBounds(0, 0, 800, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        old.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void panelShowAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelShowAllMouseClicked

    }//GEN-LAST:event_panelShowAllMouseClicked

    
    
     public void KitapListesiPaneliniOlustur(){
        DefaultTableModel model1 = (DefaultTableModel)tableKitap.getModel();
      DefaultTableModel model2 = (DefaultTableModel)tableBasili.getModel();
      DefaultTableModel model3 = (DefaultTableModel)tableEkitap.getModel();
      DefaultTableModel model4 = (DefaultTableModel)tableRoman.getModel();
      DefaultTableModel model5 = (DefaultTableModel)tableAnsiklopedi.getModel();
      DefaultTableModel model6 = (DefaultTableModel)tableDergi.getModel();
      
      int index = 0;
      
      while(InfoKitap.getKitapSize() > index){
      model1.addRow(new Object[]{kitap.get(index).getID(),kitap.get(index).getKitap_adi(),kitap.get(index).getYayim_Evi(),kitap.get(index).getBasim_tarihi()});
          index++;
          
      }
     index = 0;
      while(basili.size() > index){
       model2.addRow(new Object[]{basili.get(index).getID(),basili.get(index).getKitap_adi(),basili.get(index).getYayim_Evi(),basili.get(index).getBasim_tarihi()});
       index++;   
          
      }
      index = 0;
      while(elek.size() > index){
          
     model3.addRow(new Object[]{elek.get(index).getID(),elek.get(index).getKitap_adi(),elek.get(index).getYayim_Evi(),elek.get(index).getBasim_tarihi(),elek.get(index).getDil()});
          
     index++;
          
      }
      index = 0;
      while(roman.size() > index){
          
      model4.addRow(new Object[]{roman.get(index).getID(),roman.get(index).getKitap_adi(),roman.get(index).getYayim_Evi(),roman.get(index).getBasim_tarihi(),roman.get(index).getYazar(),roman.get(index).getTür()});
      index++;
      }
      index = 0;
     while(ansiklopedi.size() > index){
          
          model5.addRow(new Object[]{ansiklopedi.get(index).getID(),ansiklopedi.get(index).getKitap_adi(),ansiklopedi.get(index).getYayim_Evi(),ansiklopedi.get(index).getBasim_tarihi(),ansiklopedi.get(index).getKonu()});
          index++;
          
      }
      
      index = 0;
      while(dergi.size() > index){
          model6.addRow(new Object[]{dergi.get(index).getID(),dergi.get(index).getKitap_adi(),dergi.get(index).getYayim_Evi(),dergi.get(index).getBasim_tarihi(),dergi.get(index).getTürDergi(),dergi.get(index).getEditor()});
          index++;
      }
      index = 0;
    }
    public void KitapListesiPaneliBosalt(){
        
       
      DefaultTableModel model1 = (DefaultTableModel)tableKitap.getModel();
      DefaultTableModel model2 = (DefaultTableModel)tableBasili.getModel();
      DefaultTableModel model3 = (DefaultTableModel)tableEkitap.getModel();
      DefaultTableModel model4 = (DefaultTableModel)tableRoman.getModel();
      DefaultTableModel model5 = (DefaultTableModel)tableAnsiklopedi.getModel();
      DefaultTableModel model6 = (DefaultTableModel)tableDergi.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);
        model4.setRowCount(0);
        model5.setRowCount(0);
        model6.setRowCount(0);
        
    }
    
    
    
    private void btnMevcutKitaplar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMevcutKitaplar1ActionPerformed
        KitapListesiPaneliBosalt();
        jpAnapanel.setVisible(false);
        jPMevcutKitaplariGoruntule.setVisible(true);
        jpKitapAra.setVisible(false);
        jpSahipOlunanKitaplariGoruntule.setVisible(false);
        jpSifreDegis.setVisible(false);
        KitapListesiPaneliniOlustur();
    }//GEN-LAST:event_btnMevcutKitaplar1ActionPerformed
Kitap secilen = null;
public void ayarla(int secilen){
    tableKitap.clearSelection();
    tableBasili.clearSelection();
    tableEkitap.clearSelection();
    tableRoman.clearSelection();
    tableDergi.clearSelection();
    tableAnsiklopedi.clearSelection();
    
  /* switch (secilen){
       case 0 :
       tableBasili.clearSelection();
    tableEkitap.clearSelection();
    tableRoman.clearSelection();
    tableDergi.clearSelection();
    tableAnsiklopedi.clearSelection();
           break;
       case 1 :
          tableKitap.clearSelection();
           tableEkitap.clearSelection();
    tableRoman.clearSelection();
    tableDergi.clearSelection();
    tableAnsiklopedi.clearSelection();
           break;
       case 2 :
     tableKitap.clearSelection();
    tableBasili.clearSelection();
    tableRoman.clearSelection();
    tableDergi.clearSelection();
    tableAnsiklopedi.clearSelection();
           break;
      
       case 3 :
             tableKitap.clearSelection();
    tableBasili.clearSelection();
    tableEkitap.clearSelection();
    tableDergi.clearSelection();
    tableAnsiklopedi.clearSelection();
           break;
           
       case 4 :
            tableKitap.clearSelection();
    tableBasili.clearSelection();
    tableEkitap.clearSelection();
    tableRoman.clearSelection();
    tableAnsiklopedi.clearSelection();
           break;
           
       case 5:
           tableKitap.clearSelection();
    tableBasili.clearSelection();
    tableEkitap.clearSelection();
    tableRoman.clearSelection();
    tableDergi.clearSelection();
           break;
   }*/
          
    
}
int secilentable;
    private void btnShowDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailActionPerformed
        
        int []indexs = new int[6];
        indexs[0] = tableKitap.getSelectedRow();
        indexs[1] = tableBasili.getSelectedRow();
        indexs[2] = tableEkitap.getSelectedRow();
        indexs[3] = tableRoman.getSelectedRow();
        indexs[4] = tableAnsiklopedi.getSelectedRow();
        indexs[5] = tableDergi.getSelectedRow();
        
        
       for (int i = 0; i < 6; i++) {
            if (indexs[i] != -1) {
            switch (i){
                case 0:
                    secilentable = 0;
               secilen = kitap.get(indexs[i]);
                    
               break;
                case 1 :
                    secilentable = 1;
                secilen = basili.get(indexs[i]);
               
                break;
                case 2 :
                    secilentable = 2;
                secilen = elek.get(indexs[i]);
               
                break;
                case 3 :
                    secilentable = 3;
                secilen = roman.get(indexs[i]);
                
                break;
                case 4 : 
                    secilentable = 4;
                secilen = ansiklopedi.get(indexs[i]);
                
                break;
                case 5 :
                    secilentable = 5;
                secilen = dergi.get(indexs[i]);
               
                break;
                
                
            }
                   
                
            }
    
            
        }
        
        
             DahaFazla x = new DahaFazla(secilen);
        
   // this.setVisible(false);
     x.setVisible(true);        
     ayarla(secilentable);
        
        
    
    }//GEN-LAST:event_btnShowDetailActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
       jPMevcutKitaplariGoruntule.setVisible(false);
       jpAnapanel.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    public void MevcutKitaplariOlustur(){
     DefaultTableModel MODEL = (DefaultTableModel)jTableMevcutKitaplar.getModel();
        int index = 0;
       ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.baglananid, Giris.baglanansifre);
       String Tür = "";
       while(index < x.size()){
           if (x.get(index) instanceof Roman) {
               Tür = "Roman";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Roman) x.get(index)).getTür(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           else if (x.get(index) instanceof Dergi) {
               Tür = "Dergi";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Dergi) x.get(index)).getTürDergi(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           else if(x.get(index) instanceof Ansiklopedi){
               Tür = "Ansiklopedi";
               MODEL.addRow(new Object[]{x.get(index).getKitap_adi(),Tür,((Ansiklopedi) x.get(index)).getKonu(),x.get(index).getKitapAlan().getTeslimTarihi()});
           }
           index++;
       }
}
public void MevcutKitaplariSil(){
    DefaultTableModel model = (DefaultTableModel) jTableMevcutKitaplar.getModel();
    model.setRowCount(0);
}
    private void btnSahipOlunanKitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSahipOlunanKitaplarActionPerformed
       jpAnapanel.setVisible(false);
        jPMevcutKitaplariGoruntule.setVisible(false);
        jpKitapAra.setVisible(false);
        jpSahipOlunanKitaplariGoruntule.setVisible(true);
       jpSifreDegis.setVisible(false);
       MevcutKitaplariSil();
       MevcutKitaplariOlustur();
      
    }//GEN-LAST:event_btnSahipOlunanKitaplarActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        jpKitapAra.setVisible(false);
        jpAnapanel.setVisible(true);
    }//GEN-LAST:event_btnHome1ActionPerformed
    int id;
    ArrayList<Kitap> arananKitapLar = new ArrayList<Kitap>();
    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
      Kitap aranacak = null;
      
       if (jCheckSearchbyID.isSelected()) {
        aranacak = InfoKitap.KitapAra(Integer.parseInt(tfSearchedId.getText()));
        id = Integer.parseInt(tfSearchedId.getText());
        if (aranacak == null) {
           JOptionPane.showMessageDialog(null, "The searched book cannot be found !!"); 
        }
        else{
            arananKitapLar.add(InfoKitap.KitapAra(Integer.parseInt(tfSearchedId.getText())));
        }
           
        }
        
        else if(jCheckSearchByName.isSelected()){
            aranacak = InfoKitap.KitapAra(tfSearchedName.getText());
            if (aranacak == null) {
           JOptionPane.showMessageDialog(null, "The searched book cannot be found !!");
        }
            else{
                arananKitapLar.add(aranacak);
            }
        }
        
        
         if (aranacak == null) {
           JOptionPane.showMessageDialog(null, "The searched book cannot be found !!");
        }
         
         
         else{
         DefaultTableModel model = (DefaultTableModel) tableAranan.getModel();
         String Tür = "";
         
             if (aranacak instanceof Roman) {
              Tür = "Roman";
              model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Roman) aranacak).getTür()});
             }
             else if(aranacak instanceof Dergi){
                 Tür = "Dergi";
                 model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Dergi) aranacak).getTürDergi()});
                 
             }
             else if(aranacak instanceof Ansiklopedi){
                 Tür = "Ansiklopedi";
                 model.addRow(new Object[]{aranacak.getKitap_adi(),aranacak.getYayim_Evi(),Tür,((Ansiklopedi) aranacak).getKonu()});
             }
             
         }
         

    }//GEN-LAST:event_btnAraActionPerformed
public static Kitap aranankitapNe = null;

    private void btnOduncAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncAlActionPerformed
       int index = tableAranan.getSelectedRow();
        
        if (index != -1) {
            aranankitapNe = arananKitapLar.get(index);
            if (InfoKitap.KitapOduncVer(aranankitapNe, InfoKullanici.KitapAlmakİsteyeniDondur(Giris.baglananid, Giris.baglanansifre))) {
                JOptionPane.showMessageDialog(null, "Borrowing book operation is successful");
            }
            else{
                JOptionPane.showMessageDialog(null, "The book is already borrowed !!");
            }
 
            
        }

    }//GEN-LAST:event_btnOduncAlActionPerformed

    private void jCheckSearchbyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSearchbyIDActionPerformed
       jCheckSearchbyID.setSelected(true);
       jCheckSearchByName.setSelected(false);
       jpanelSecimler.setVisible(true);
       PanelIDileAra.setVisible(true);
       panelAdİleAra.setVisible(false);
    }//GEN-LAST:event_jCheckSearchbyIDActionPerformed

    private void jCheckSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSearchByNameActionPerformed
        jCheckSearchbyID.setSelected(false);
       jCheckSearchByName.setSelected(true);
          jpanelSecimler.setVisible(true);
       PanelIDileAra.setVisible(false);
       panelAdİleAra.setVisible(true);
    }//GEN-LAST:event_jCheckSearchByNameActionPerformed

    private void btnKitapAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapAraActionPerformed
        // TODO add your handling code here:
        jpAnapanel.setVisible(false);
        jPMevcutKitaplariGoruntule.setVisible(false);
        jpKitapAra.setVisible(true);
        jpSahipOlunanKitaplariGoruntule.setVisible(false);
        jpSifreDegis.setVisible(false);
    }//GEN-LAST:event_btnKitapAraActionPerformed

    private void btnShowMoreDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMoreDetailActionPerformed
int index = jTableMevcutKitaplar.getSelectedRow();
    DahaFazla abc;
    ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.baglananid, Giris.baglanansifre);
        if (index != -1) {
          abc = new DahaFazla(x.get(index));
          abc.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please make a selection !!");
        }     

    }//GEN-LAST:event_btnShowMoreDetailActionPerformed

    private void btnIadeEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIadeEtActionPerformed
        Kitap iadeEt;
       int index = jTableMevcutKitaplar.getSelectedRow();
        if (index != -1) {
          ArrayList<Kitap> x = InfoKitap.getOduncVerilen(Giris.baglananid, Giris.baglanansifre);
          iadeEt = x.get(index);
          InfoKitap.KitapGeriAl(iadeEt);
          
        JOptionPane.showMessageDialog(null, "Lending book operation is successful !!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error !!");
        }
    }//GEN-LAST:event_btnIadeEtActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        jpSahipOlunanKitaplariGoruntule.setVisible(false);
        jpAnapanel.setVisible(true);
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnShowMoreDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMoreDetail1ActionPerformed
         String x = String.valueOf(jPassEskiKullaniciSifre.getPassword());
        String y = String.valueOf(jPassYeniKullaniciSifre.getPassword());
        String z = String.valueOf(jPassYeniKullaniciSifre2.getPassword());
        
        if (x.equals(Giris.baglanansifre)) {
            if (y.equals(z)) {
             int reply = JOptionPane.showConfirmDialog(null, "Your password will be changed", "Sure ?", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_NO_OPTION) {
                   InfoKullanici.KullaniciSifreDegis(Giris.baglananid,Giris.baglanansifre, y);
                   JOptionPane.showMessageDialog(null, "Operation is successful");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Operation cancelled");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Passwords are not matching !!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong password");
        }
        
    }//GEN-LAST:event_btnShowMoreDetail1ActionPerformed

    private void btnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome3ActionPerformed
       jpSifreDegis.setVisible(false);
       jpAnapanel.setVisible(true);
    }//GEN-LAST:event_btnHome3ActionPerformed

    private void btnSifreDegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSifreDegisActionPerformed
        jpAnapanel.setVisible(false);
        jPMevcutKitaplariGoruntule.setVisible(false);
        jpKitapAra.setVisible(false);
        jpSahipOlunanKitaplariGoruntule.setVisible(false);
       jpSifreDegis.setVisible(true);
    }//GEN-LAST:event_btnSifreDegisActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIDileAra;
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnIadeEt;
    private javax.swing.JButton btnKitapAra;
    private javax.swing.JButton btnMevcutKitaplar1;
    private javax.swing.JButton btnOduncAl;
    private javax.swing.JButton btnSahipOlunanKitaplar;
    private javax.swing.JButton btnShowDetail;
    private javax.swing.JButton btnShowMoreDetail;
    private javax.swing.JButton btnShowMoreDetail1;
    private javax.swing.JButton btnSifreDegis;
    private javax.swing.JCheckBox jCheckSearchByName;
    private javax.swing.JCheckBox jCheckSearchbyID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPMevcutKitaplariGoruntule;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassEskiKullaniciSifre;
    private javax.swing.JPasswordField jPassYeniKullaniciSifre;
    private javax.swing.JPasswordField jPassYeniKullaniciSifre2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMevcutKitaplar;
    private javax.swing.JPanel jpAnapanel;
    private javax.swing.JPanel jpKitapAra;
    private javax.swing.JPanel jpSahipOlunanKitaplariGoruntule;
    private javax.swing.JPanel jpSifreDegis;
    private javax.swing.JPanel jpanelSecimler;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lbluserid;
    private javax.swing.JLabel lbluserid1;
    private javax.swing.JLabel lbluserid2;
    private javax.swing.JLabel lbluserid3;
    private javax.swing.JLabel lbluserid4;
    private javax.swing.JLabel lbluserid5;
    private javax.swing.JLabel lbluserid6;
    private javax.swing.JLabel lbluserid7;
    private javax.swing.JPanel panelAdİleAra;
    private javax.swing.JPanel panelShowAll;
    private javax.swing.JPanel panelShowAnsiklopedi;
    private javax.swing.JPanel panelShowBasili;
    private javax.swing.JPanel panelShowDergi;
    private javax.swing.JPanel panelShowEKitap;
    private javax.swing.JPanel panelShowRoman;
    private javax.swing.JTable tableAnsiklopedi;
    private javax.swing.JTable tableAranan;
    private javax.swing.JTable tableBasili;
    private javax.swing.JTable tableDergi;
    private javax.swing.JTable tableEkitap;
    private javax.swing.JTable tableKitap;
    private javax.swing.JTable tableRoman;
    private javax.swing.JTextField tfSearchedId;
    private javax.swing.JTextField tfSearchedName;
    // End of variables declaration//GEN-END:variables
}
