/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ARAYUZLER;

import Arayuzler.*;
import Kullanici.Normal;
import System.InfoKullanici;
import javax.swing.JOptionPane;

/**
 *
 * @author OGUZ
 */
public class YeniSifre extends javax.swing.JFrame {

    /**
     * Creates new form YeniSifre
     */
    Admin_GUI eski;
    Normal zed;
    public YeniSifre(Admin_GUI x,Normal Ye) {
        initComponents();
        eski = x;
        zed = Ye;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(401, 301));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ENTER AGAIN :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 83, 124, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ENTER NEW PASSWORD :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 37, 160, 40);

        jTextField1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 50, 161, 21);

        jTextField2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 100, 161, 21);

        jButton1.setBackground(new java.awt.Color(0, 155, 167));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 193, 170, 47);

        jButton2.setBackground(new java.awt.Color(0, 155, 167));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 193, 170, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/Webp.net-resizeimage.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
      
    }//GEN-LAST:event_jButton2ActionPerformed
String sifrem;
    public void YeniSifreVer(Normal Kullanici,String Yenisifre){
       String x = Kullanici.getKullanici_id();
       String y = Kullanici.getKullanici_parola();
        InfoKullanici.KullaniciSifreDegis(x, y, Yenisifre);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.getText().equals(jTextField2.getText())) {
            
            sifrem = jTextField1.getText();
            YeniSifreVer(zed, sifrem);
            JOptionPane.showMessageDialog(null, "Changing password operation is successful");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
public String getSifre(){
    return sifrem;
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
